default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  pool: 5
  username: ubuntu
  password: password

development:
  <<: *default
  database: newRailsApp_development
test:
  <<: *default
  database: newRailsApp_test
production:
  <<: *default
  database: harak_patil_in
